apiVersion: 1
contactPoints:
  - orgId: 1
    name: discord-anomaly
    receivers:
      - uid: discord-anomaly-uid
        type: discord
        settings:
          url: "https://discord.com/api/webhooks/1424649617848406016/_FHz0D3Pq4AWm0Q85JCXWKMdJWN-EW-rKjxNoK4wt5qnhUkobSAZCBwwhV83ORWoivhw"
          message: |
            {{ if gt (len .Alerts.Firing) 0 }}
            🔴 **ANOMALY ALERT**
            {{ range .Alerts.Firing }}
            **Datastream:** {{ index .Labels "datastream" }}
            **Count:** {{ printf "%.0f" (index .Values "A").Value }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            ---
            {{ end }}
            {{ end }}
        disableResolveMessage: false
