input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  mutate {
    rename => {
      "[message]" => "[@metadata][raw_message]"
    }
  }
  if ![datastream] {
    mutate { add_field => { "datastream" => "unknown" } }
  }
  if ![timestamp] {
    mutate { add_field => { "timestamp" => "%{@timestamp}" } }
  }
}

output {
  http {
    http_method => "post"
    url => "http://parser:8000/ingest"
    format => "json"
    mapping => {
      "message" => "%{[@metadata][raw_message]}"
      "datastream" => "%{[datastream]}"
      "timestamp" => "%{timestamp}"
    }
  }
}
