input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => {
      "[@metadata][datastream]" => "%{[fields][datastream]}"
    }
  }
  if ![fields][datastream] {
    mutate { add_field => { "[@metadata][datastream]" => "unknown" } }
  }
}

output {
  http {
    http_method => "post"
    url => "http://drain3:8000/ingest"
    format => "json"
    mapping => {
      "message" => "%{message}"
      "datastream" => "%{[@metadata][datastream]}"
      "timestamp" => "%{@timestamp}"
    }
  }
}
