{
 "title": "Structured Logs",
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "datastream",
    "label": "Datastream",
    "query": "label_values({datastream=~\".+\"}, datastream)"
   },
   {
    "name": "event_template",
    "label": "Event Template",
    "query": "label_values({datastream=~\"$datastream\"}, EventTemplate)"
   }
  ]
 },
 "panels": [
  {
   "title": "Live Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{datastream=~\"$datastream\", EventTemplate=~\"$event_template\"}"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (EventTemplate) (count_over_time({datastream=~\"$datastream\", EventTemplate=~\"$event_template\"}[$__interval]))",
     "legendFormat": "{{EventTemplate}}"
    }
   ]
  },
  {
   "title": "Top Event Templates",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (EventTemplate, EventTemplateText) (count_over_time({datastream=~\"$datastream\", EventTemplate=~\"$event_template\"}[$__range]))",
     "legendFormat": "{{EventTemplateText}}"
    }
   ]
  }
 ]
}